// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVEPn-pxJJKaoguS_0cLNiS6XZr6SyKU4',
    appId: '1:349636619374:web:44ca7f07251a33d57f8a7f',
    messagingSenderId: '349636619374',
    projectId: 'auth-375d5',
    authDomain: 'auth-375d5.firebaseapp.com',
    storageBucket: 'auth-375d5.appspot.com',
    measurementId: 'G-XDMR4HT4QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrnnarYTiRTKKBRKuHzti-E1cjcMbe_S4',
    appId: '1:349636619374:android:38f0125f6347b8107f8a7f',
    messagingSenderId: '349636619374',
    projectId: 'auth-375d5',
    storageBucket: 'auth-375d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSGafyFFebjVtYZPmJdjz6JEj5VZujM64',
    appId: '1:349636619374:ios:8707ae8dd82d32677f8a7f',
    messagingSenderId: '349636619374',
    projectId: 'auth-375d5',
    storageBucket: 'auth-375d5.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSGafyFFebjVtYZPmJdjz6JEj5VZujM64',
    appId: '1:349636619374:ios:8707ae8dd82d32677f8a7f',
    messagingSenderId: '349636619374',
    projectId: 'auth-375d5',
    storageBucket: 'auth-375d5.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVEPn-pxJJKaoguS_0cLNiS6XZr6SyKU4',
    appId: '1:349636619374:web:0e86abc67371a34f7f8a7f',
    messagingSenderId: '349636619374',
    projectId: 'auth-375d5',
    authDomain: 'auth-375d5.firebaseapp.com',
    storageBucket: 'auth-375d5.appspot.com',
    measurementId: 'G-CBL0G7R58Y',
  );
}
